include("transposition.jl")
include("cipher.jl")
include("cracks.jl")
include("periodic_substitution.jl")
using Combinatorics

A = "JUCGC UKXYI WYQQF EEKQO CGIEF YKKSL UUYSL VFCOC XCGUG TEDGM DPKVG CEWII VBLIA RUHZG IRUIY ISGCH TRLVU UMXKS QSLCH TCHEP OVEUC TSWJC XHICH CYPRP EUDTM YCXAA IEVSZ USKJY CGIRU IYHXF RUYXG KJYCT ECKML IMFPN SPXKC FWBEU IYHPW NQLVX RXHIC ILVEC LRLRP APSIM GLJIL ZPAQX VJVCE BIRPN EWEKY YSPHJ VOXQP VFIYH SDGNS XRXOO NWFZI APGXY CHLQE EMZCP YUCHO HITQH OXXDG UYIXY CNEWI IGQLH EJGLT DYJTC DZMNQ OWSFV VUVTR ZPCDI MCNQL HRKGH EXVVN SDJVV YBJWE ITSSP HTQGP QYKCZ ETVKJ YWPWK HYHSE PUCSP HIGUD HYIGX XNWVN ZEWEK JYHPW EVUMD YKVIE JVEOY TCMJV CWALR FHETB GNUTC IUOSC TEJQH DUSIC VDRSE FCYVT VTBLE WGCLE ACSGW LJWVK QLHRK UOCTS WVBPB QPUYW UFLVC ELEJE FPPVK JUEWE ITSHP WYGLP QITCO DTLVY UYIIU VIFCH VTMEP RUPIE QITCO DTLVY UYIIU VIEJV EOYTC SLTWZ JWZPM TCXYG URTRT AQPGI LPFTZ ICANZ QIKJU EHCDR UEWIK KWEWE KYUDP WJWGT CKKJY JZRVY CHPWF PNSTV LPIQR SLTMP WEITS SPHEQ NMTIE EFPPV RDIFI XYCND DXYGL PLEJU NTAPR EBLCG VVBLI MTQOW SJCAO YSIIV BPXVI CXLGF LVHZI MWKQL HGRWA SIWEQ IAXRX QHZCI FHNST MIQQY PWWQL EPPCO UOVIK JYCTA VTYEL SGQMD XFZNC EXIJJ YXXKY VVPDR KJYWT ZVNUY SQRAV PILVM COCEG CHOXR KKGTS EKKIY LIIGU WATRT NZUEE QJPGE KKIYX XNCMC DYXJY CILRP UYNXY KHRQS JUQZJ PUFIM JXKJY LBIIK WLCWY CPPSM WHYCT RKVLL SMKKI YHSEV BPDXY GLSPR UVBPR MRFIY IYJWU WACXG NEDME XYDIM XCNPJ WTKNT OIEUN SPXZU NSTTI QPTCG VQZEW IWDCL CHYQG PAEEF MPRYI KNJHS VKNST VKJYC TMJCF TCOSG NHTIE CHYPP PPHLC HRHIC TMXPJ ZLIIQ LEPPC OUOVI NCMCJ REKHR PHZUN TCGKN SODHX AIATV RVCZC XYGIE WIIRI DHMSK FTICZ UNSPX KCFWB EUIYT HVLPH TCKJQ GPILZ PAZUJ SQIVH QRAVP PWRFI FQPVC APCXF TJZHW ZDFJP WRUCO TLLUN WTRVK NSTVZ UUEIV RENTK IRPXP XXYGL HPCYG QZJPU PNEWE EMODU SIIYE IMEIC YKSCX YOXXZ UNPBT KKHRI SKTSE DLREE TCXFV BPAEE IFPNW VTPPG WKQZT CHFWN XDVVC VZJXK CFWBE UIYMJ XKJYY PQVYU DRPVC LWNET QPPGE EFUDT EIEBH DYCFN CXKXG LLAPJ QLEHS WCFLG QJKHD IIRFC DEIEV UHWMC GLPHI RTWSX RXVBP CEDGN ZHIVK ZTIWL IAPHX VFNST RRVOC TSWJC DDTVT UEXSE KNSXR BKNXJ WKLOD IFVCW ZXRTK XPCGV VBLIX YGHLB IRPHL HQZVB EJVEG XFEME VBPWM JVICN FFQED AMEMY OLMKJ CEXXJ CZLXV CAWZB QFPHL BISWN TLSEF YCXJR PHLWE UUYPC MKYBP CWYGX TSLVT IHCGY GWVHS EVUWA QRFAP XJJQC EBMXJ NSPZV UJLGO VFUOT IGGLT CXVTY DIEEF GLNFV VBLIA RUYYD YXJNZ AIRFO DWIIG CSDTV VIRTX REBLC GVVIL HOYGL EWIVK ASIIV PNSRI EVOCN EEPUD BMKJM PTQJV ISPZV DYPCE DGGMT VFHNS TGLNJ PGWGA LTCKI GMADR JKVWT JFTMT VRRNF TCKSG NHTIE CAPCX JVBPA MWGIQ PGYKY QIICN YCBYJ VBLKI JGYXT HCKAS ISEFL LBETQ GAPVV FNZIL RVUYS QRAVP XRMGM EXKRV CYVXR NFXPH XGLPA MVXYO ILVDI CTHFO NSTQF TYTIL ZPELQ SLVCE ILVOI CTGVT NLXRZ CGEWE KVBPK ELNNT HETQG XJRZE UEXSE UMJHX VOQSP XZFIY IOEQQ THAYG NSTVK CFWBE UIYHP WGCLE DJKJY DNWKG GZGMW JYHPW AWMEX RMGME XKRVC YVMKC HOXWZ VFTKI FTDFH XRJCD ISIKW LGXVH UNIMJ VUWAQ RFAPP XIGUD JVVJO YIIIV BPRYC RYCGM EIGFH XYCPP WEUCZ FCHKQ JLNEX GHEHE EFCDJ TGQMP XXZUH ZIMDR IDHMS NYEWE KVBPA STCNT DRFHN SPXDQ HPNMJ UIXTL FYYYR SUGXT CXYGV ZMIJQ LTHLV WMTCK KJYGP YCVNZ EEJUC YIICN CRTRT GUNGS JUUYT XNQLV XJJQB ZLMJJ YODME ICEPR UKMEW MJQZQ XGZCF ZGLRX YHTJF WHODY IUYWK IJCNC PMKQL XPCSG QSTRY CLCNV VUOCU ETGMH TAZNF QXRUQ OE"
B = "OUEVE BEKCO AAFEO ITIBE HIAKU TNOTQ DRHKR ITEIH AEGOJ ARSHN TTEES TAOMO SEODU EDTWM GTCWO CCWDE TFAEI EHIOI CIATC HFLNN OKNIA TVIOU ADTUA ATTRO AHWNF ASHLD IIESE TTTLR OMWTF IEAOY ALARM YAHUH AKKWI NLDTE NNKYL DTABW WNOIO NIRIS HBAHO GNMNU KLKEE GTSEI EATRH IGLTE NSDAR FHAIL WNIEW DBIBN RATUN FANTC YRHEA ERAST MTHUC ASEVG SIMOS IEETE DMEOR GDONE SBPTM ETREU AAVTC WATNE DTENO UTTTE FETEH EEWAT MTHRT BEHAA YSABA NTWOR DABSA LSNYP IIBNA SYWLE KSDTA TTOEE OSHTS HETLL EAWAT WHEOO VIFDB NOTUS OAEWH LEUVN ETEAA ODMRU DYHNR EHNVR ETATG HDAHT HEEOR SONOR EUEBE PIIDT NZSHS LEERP HNCDL OHOGO HUOTA TAVTG FWDDA TUIDE NNEHH IATTC RIHNO EDWOD VTLDN NDSBA IAIEI OILNT EMIRY TTEYT STHIR KWCUT LBHSE BADNT AERTI EAEAE WDACN AKSEU TEBAA BAETT STDMH TTARF YNYHN EFHSG EYUSS OSLNI NEIAD ARAWW HIADO DKTRZ CUANI TIEUH AETSN OTAIO NOTAD LRROE FIFDA MOTHE TAONR UIALT YEDLH UXTEL LNTTW TWSGV BEHOT IAIEO AFAOE AEOFN SCHNL EBNFS DTTEN FHGOO RAEEM TDTEC OVNDT KXTOA IFOAU REDOM NSEII TSUIR PBIED AYTCH HLNRU ANNWB HTITK OEUOT WGWTR HDSTS QIMEA HASEE LKRIS UNIII TAATD HSHIN HERWH ONPLE KTDAE RODIE PDAFE TLETP IRGII CCGYT EEAEN RINNH TICIS CSRNA NNHEA LLTCH IEOFD ILEMO YEKEH DRSIB NILSE TATDP EWNDR VHFAE EERNL HERNE IYTTD TDYSO IEUET OAUAF IAHID DHGNT YNNTN TGEFI LOTTW OTEPH NLWIV ERWKH ARTGE DTHEN EOONA DBHOU OTEEE TNEHK LRNOA DNNHI TBAEO TEGTN TMGTI HKAEE ICNID OMXEI LOOEE TDLTP YAPDS HDFNE ATARF CITBR UETSE EIDUI NHBEL TLGAL FCMIA TAOOE IDTSG KDHEH TCEDT ISAHI IPJBE OOAWO UIUON NNWWT CUTSU ROAMT KOOOH TIHHL RMBDI EDYUO EAAMO SYNES DLIHI TTETR TEGTE AESBL HELSK SNSIJ OLNAA WSSTE GSTUS EADMG ATINI EESPB TMHOT IWADD TEAST AATHL AHLGS ETNAL EPDAD NISUL ENUGW VAWTD NORLI OCCHN ENAOT ISICS IMTEH ADGKA FMION AERIN TGTES OTHOO IIRHA"

A_CRACK = "HARRY DIDNT SHOWU PATOU RREND EZVOU SANDH EDIDN TLEAV EAMES SAGEE ITHER THATW ASNOR EASON TOPAN ICHES ABIGB OYAND CANTA KECAR EOFHI MSELF INANY CASEI HADPL ENTYO FOTHE RREAS ONSTO PANIC THERE ALISA TIONT HATTA LLMAD GEWAS WORKI NGFOR THECI ACHAN GEDEV ERYTH INGFI RSTIT MEANT THATW EHADS TUMBL EDONS OMETH INGMU CHBIG GERTH ANABA NKFRA UDAND SECON DITME ANTTH ATTHE REWAS ASERI OUSRI SKIWO ULDBE TAKEN INIST ILLWA SNTEN TIREL YSURE WHYHA RRYHA DCOME BUTAF TERTH ELAST FEWDA YSIHA DREAS SURED MYSEL FTHAT HEWAS NTABO UTTOT URNME INIST ILLHA DNTEX PLAIN EDMYR EASON SFORA BSCON DINGP ERHAP SPART LYBEC AUSEI WASNT SUREO FTHEM MYSEL FBUTI TWASC LEART HATHA RRYWA SHERE BECAU SEHEW ANTED TOUND ERSTA NDNOT BECAU SEHEW ANTED TOTUR NMEIN OURCO USINS INTHE AGENC YWERE UNLIK ELYTO BETHA TSYMP ATHET ICTHA TWASA SSUMI NGTHE YKNEW IWASO NTHER UNOFC OURSE HARRY HADNO TBEEN CLEAR ABOUT THATS OTHER EWASS TILLA CHANC ETHAT ICOUL DFLYU NDERT HEIRR ADARB UTNOT IFIWA SCAUG HTSNO OPING ONONE OFTHE IROWN ASFOR TALLM ADGET HEREW ERETW OPOSS IBILI TIESH EMIGH TBEON THELE VELAN DMAYB ETHEK IDNAP ANDIN TIMID ATION WEREA LLPAR TOFAN OPERA TIONI TWASR OUGHE RTHAN ANYTH INGBO SSWOU LDDOB UTTHE AMERI CANSH AVEDI FFERE NTTRA DITIO NSONT HEOTH ERHAN DTHEC IADON TUSUA LLYGE TTOIN VESTI GATEU SCITI ZENST HATIS THEPR OVINC EOFTH EFBIA NDHOM ELAND SECUR ITYSO EITHE RTHER EISAL INKBE TWEEN ANNAL YNNAN DAFOR EIGNP OWERO RTALL MADGE WASRU NNING ADIST INCTL YDODG YOPER ATION THEOT HERPO SSIBI LITYI STHAT TALLM ADGEI SRUNN INGSO METHI NGOFF BOOKS MAYBE ASADO UBLEA GENTO RPOSS IBLYA SASID EHUST LENEI THERI SATTR ACTIV EANDE ITHER WAYHE WOULD NTTHA NKUSF ORGET TINGI NVOLV EDITI STEMP TINGT OTRYT OHACK INTOT HELAN GLEYS ERVER STOFI NDOUT MOREA BOUTT ALLMA DGEBU TTHEN AMEWA SCLEA RLYAC OVERA NDASE ARCHW OULDT RIGGE RALLS ORTSO FALAR MSINS TEADI SPENT AWHIL ERESE ARCHI NGTHE NAMET OSEEI FITSU GGEST EDTHE NATUR EOFHI SOPER ATION ITHIN KITMU STJUS TBEAC OINCI DENCE THATT HENAM EANNA SMITH TURNE DUPIN THEHI STORY BOOKS LINKE DWITH ITITS AFAIR LYCOM MONNA MEBUT IWOND ERIFA NNAHA DSEEN ITWHE NSHED IDHER OWNCH ECKSO NTALL MADGE IFSOI TMIGH THAVE SPARK EDADE EPERI NTERE STAND MAYBE THATW ASENO UGHTO LEADU SHERE IHOPE TOGET ACHAN CETOA SKHER THEEI GHTEE NTHCE NTURY ANNAS MITHS EEMST OHAVE BEENA MEMBE ROFTH ECULP ERSPY RINGR ESPON SIBLE FORSI GNALL INGBE TWEEN AGENT STHEL IFEOF ACHIE FTELL ERMUS THAVE SEEME DLIGH TONDR AMACO MPARE DTOTH ATAND MAYBE INVES TIGAT INGTA LLMAD GEREL IEVED THEBO REDOM THEMO REITH INKAB OUTIT THEMO RECER TAINI AMTHA TTHEV AULTI SACOM MUNIC ATION SSYST EMWHA TIDON TKNOW ISWHE THERT ALLMA DGEWA SPART OFTHE SYSTE MORIF HEWAS JUSTI NVEST IGATI NGITA NDISI TLIVE ORJUS TAHIS TORIC ARTEF ACTIS TALLM ADGEA TREAS UREHU NTERT HECUL PERRI NGMUS THAVE HADAF UNDTO PAYAG ENTSA NDISU PPOSE ITISN OTIMP OSSIB LETHA TTHEL OCATI ONOFT HATMO NEYIS SOMEH OWENC ODEDI NTHEB OXESO RISHE USING THEVA ULTTO PASSI NTELL IGENC EACRO SSANE TWORK IFSOH OWISH EDOIN GITAN DISTH ISOFF ICIAL ORHAV EWEFO UNDOU RSELV ESATR AITOR MAYBE WHENH ARRYR ESURF ACESW EWILL FINDO UT"
A_MESSAGE = "What do you think, rogue or traitor? And what is Tallmadge up to at the bank?"

B_TIPS = "Factors are your friend! I broke the text into blocks and encrypted each block separately to reduce the chance of errors."

T = Txt(B)
tokenise!(T)

# B length is 1435, which is 5 * 7 * 41
# Given orthodot ≈ 1, probably basic periodic substitution, no transposition, with period 5 or 7 (or both?)

perms5 = Columnar.(permutations(collect(1:5)))
perms7 = Columnar.(permutations(collect(1:7)))

max_f = nothing
max_p = nothing
max_T = nothing

for p in perms5
    for q in perms7
        global max_f, max_p, max_T, U
        U = q(p(T))
        f = quadgramlog(U)
        if isnothing(max_f) || f > max_f
            max_f = f
            max_p = p
            max_q = q
            max_T = deepcopy(U)
        end

        U = p(q(T))
        f = quadgramlog(U)
        if isnothing(max_f) || f > max_f
            max_f = f
            max_p = p
            max_q = q
            max_T = deepcopy(U)
        end
    end
    println(findfirst(==(p), perms5))
end